# Generated by Django 5.0.4 on 2024-04-28 18:40

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text_short', models.TextField()),
                ('information', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers_about/')),
                ('file', models.FileField(blank=True, null=True, upload_to='files_aboutus/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('customers_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
