# Generated by Django 5.0.4 on 2024-04-29 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='gallery_aboutus/')),
                ('aboutus', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.aboutus')),
            ],
        ),
    ]
