# Generated by Django 5.0.4 on 2024-05-09 07:50

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=25, verbose_name='phone_number')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth_date')),
                ('gender', models.BooleanField(blank=True, null=True)),
                ('information', models.TextField(verbose_name='information')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='customer_picture/', verbose_name='customer_picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='service.customer')),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('postalcode', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='description')),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('picture_category', models.ImageField(blank=True, null=True, upload_to='category_picture/')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='service.category')),
            ],
        ),
        migrations.CreateModel(
            name='PersonService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='personservice_picture/')),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('information_short', models.TextField(blank=True, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('pinterest', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags_service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SampleGalleryPersonService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='name_image')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description_image')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('Skill_level', models.IntegerField()),
                ('personservice', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='skill_personservice', to='service.personservice')),
            ],
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='slug_service')),
                ('info', models.TextField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon_typeservice/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='price')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime_created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='datetime_modified')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='servicepicture/', verbose_name='servicepicture')),
                ('status', models.CharField(choices=[('pub', 'published'), ('drf', 'draft')], default='pub', max_length=3, verbose_name='status_service')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_service', to='service.category', verbose_name='category_service')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags_service')),
            ],
        ),
        migrations.CreateModel(
            name='ReserveService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserve_service', to='service.typeservice')),
            ],
        ),
        migrations.AddField(
            model_name='personservice',
            name='typeservice',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='typeservice_personservice', to='service.typeservice'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('w', 'Waiting'), ('a', 'Approved'), ('na', 'Not Approved')], default='w', max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(verbose_name='Comment Text')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('typeservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='service.typeservice')),
            ],
        ),
    ]
