# Generated by Django 5.0.4 on 2024-05-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personservice',
            name='experience',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
