# Generated by Django 5.0.4 on 2024-04-28 18:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeservice',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeservice',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon_typeservice/'),
        ),
    ]
