# Generated by Django 5.0.4 on 2024-05-01 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_reserveservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserve_service', to='service.typeservice'),
        ),
    ]
