# Generated by Django 5.0.4 on 2024-05-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_reserveservice_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserveservice',
            name='service',
        ),
    ]
