# Generated by Django 5.0.4 on 2024-05-01 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_reserveservice_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveservice',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reserve_service', to='service.typeservice'),
            preserve_default=False,
        ),
    ]
