# Generated by Django 5.0.4 on 2024-05-02 08:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_reserveservice_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personservice',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='personservice',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='personservice',
            name='information',
        ),
        migrations.RemoveField(
            model_name='personservice',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='personservice',
            name='picture',
        ),
        migrations.AddField(
            model_name='personservice',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personservice',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personservice',
            name='image',
            field=models.ImageField(default=1, upload_to='personservice_picture/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personservice',
            name='information_short',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personservice',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personservice',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personservice',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='personservice',
            name='pinterest',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
