# Generated by Django 5.0.4 on 2024-05-02 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_personservice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personservice',
            name='user',
        ),
        migrations.AlterField(
            model_name='personservice',
            name='typeservice',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='typeservice_personservice', to='service.typeservice'),
        ),
    ]
