# Generated by Django 5.0.4 on 2024-05-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_personservice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveservice',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
