# Generated by Django 5.0.4 on 2024-05-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_reserveservice_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personservice',
            name='typeservice',
        ),
    ]
