# Generated by Django 5.0.4 on 2024-05-07 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_remove_personservice_typeservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='personservice',
            name='typeservice',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='typeservice_personservice', to='service.typeservice'),
            preserve_default=False,
        ),
    ]
