# Generated by Django 5.0.4 on 2024-05-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_personservice_typeservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='personservice',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
    ]
