# Generated by Django 5.0.4 on 2024-05-07 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_personservice_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personservice',
            name='slug',
        ),
    ]
